#!/bin/sh
#mysqldump -uroot -ppublic -h192.168.1.31 monit | sed 's/192\.168\.1\.31/localhost/g' | mysql -uroot -ppublic monit;
cat ../config/database.yml | sed 's/\/var\/run\/mysqld\/mysqld\.sock/\/tmp\/mysql.sock/g' | sed 's/192\.168\.1\.31/localhost/g' > ../config/database.yml;
