#!/bin/bash
if [ $# != 1 ]; then
  echo "usage: start nodename"
  exit 1
fi

#define default configuration
POLL=true
SMP=disable
ERL_MAX_PORTS=32000
ERL_PROCESSES=250000
ERL_MAX_ETS_TABLES=1400
NODE_NAME=$1
ROOTDIR=/opt/monit/node

# define environment variables
MONIT_HOME=$ROOTDIR
DATETIME=`date "+%Y%m%d-%H%M%S"`
SASL_LOG_PATH="$ROOTDIR/var/log/${NODE_NAME}_sasl.log"
ERL_CRASH_DUMP="$ROOTDIR/var/log/erl_crash_$DATETIME.dump"
MONIT_SO_PATH="$ROOTDIR/priv/$ARCHDIR/lib"
MONIT_DB="$ROOTDIR/var/data/$NODE_NAME"
MONIT_CONFIG_PATH="$ROOTDIR/etc/monit/node"
MONIT_LOG_LEVEL=3
MONIT_LOG_PATH="$ROOTDIR/var/log/${NODE_NAME}.log"

# export global variables
export MONIT_HOME
export MONIT_SO_PATH
export SASL_LOG_PATH
export ERL_MAX_PORTS
export ERL_MAX_ETS_TABLES
export ERL_CRASH_DUMP

[ -d "$MONIT_DB" ] || mkdir -p "$MONIT_DB"

erl -noinput -detached -smp $SMP +P $ERL_PROCESSES +K $POLL -sname $NODE_NAME -pa $ROOTDIR/ebin -mnesia dir "\"$MONIT_DB\"" -config $MONIT_CONFIG_PATH -boot start_sasl -sasl sasl_error_logger \{file,"\"var/log/${NODE_NAME}_sasl.log\""\} -s reloader start -s monit_node_app start -log_level $MONIT_LOG_LEVEL -log_path $MONIT_LOG_PATH
#-noinput -detached

